{% set name = "trainstation" %}
{% set version = "1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trainstation-{{ version }}.tar.gz
  sha256: fe84024aea1d1af200cc5290023e8e7930ce21c0d4401d368a8e3ab231922306

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - numpy >=1.12
    - python >={{ python_min }}
    - scikit-learn
    - scipy

test:
  imports:
    - trainstation
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://trainstation.materialsmodeling.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convenient training of linear models
  description: |
    trainstation is a tool that allows the efficient construction of 
    linear models. It provides supplementary functionality for handling 
    data and model metrics and relies on the scikit-learn library for the
    actual training. trainstation has been originally developed to aid
    the construction of force constant (via hiphive) andcluster expansions
    (via icet). Since it has proven to be valuable in more general
    contexts and to simplify the maintenance of the two aforementioned
    packages, the functionality has been moved into a separate package. 
  doc_url: http://trainstation.materialsmodeling.org/
  dev_url: https://gitlab.com/materials-modeling/trainstation

extra:
  recipe-maintainers:
    - jan-janssen
